---

- name: clamav workspace
  include_tasks: workspace.yml
  vars:
    workspace_items: "{{ clamav_workspace_items }}"


- name: deploy conf
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: "{{ root_group }}"
    mode: "{{ item.mode }}"
  loop:
    - src: clamd/clamd.conf
      dest: "{{ clamav_clamd_conf }}"
      owner: root
      group: "{{ root_group }}"
      mode: "0644"
    - src: freshclam/freshclam.conf
      dest: "{{ clamav_freshclam_conf }}"
      owner: root
      group: "{{ root_group }}"
      mode: "0644"
  register: t_clamav_conf


- name: check clamav db
  stat:
    path: "{{ clamav_clamav_db_dir }}/main.cvd"
  register: t_clamav_stat_db_daily

- name: init clamav db
  command:
    cmd: freshclam
  when: not t_clamav_stat_db_daily.stat.exists


- name: deploy clamscanner
  template:
    src: scripts/clamdscanner
    dest: "{{ clamav_clamdscanner_clam_bin }}"
    owner: root
    group: "{{ root_group }}"
    mode: "0755"
  vars:
    clamav_clamdscanner_cmd: clamscan
    clamav_clamdscanner_opt1: "--recursive"

- name: deploy clamdscanner
  template:
    src: scripts/clamdscanner
    dest: "{{ clamav_clamdscanner_clamd_bin }}"
    owner: root
    group: "{{ root_group }}"
    mode: "0755"
  vars:
    clamav_clamdscanner_cmd: clamdscan
    clamav_clamdscanner_opt1: "--fdpass"
