#!/bin/sh

SCRIPT_PATH=$(cd "${1%/*}"; echo $PWD)

CONF="{{ freshclam_conf }}"
DATADIR="{{ clamav_db_dir }}"

exec 2>&1
exec fghack setuidgid {{ clamav_user }} freshclam \
     --daemon \
     --config-file "$CONF" \
     --datadir="$DATADIR" \
     --checks=4 \
     --quiet \
     --stdout
     # --daemon-notify=$CLAMCONF
